### ISSUE TITLE
Not working in Xcode 10 beta 5

### ISSUE THREAD

**Issue by moheny** [robomex/ARKit-2-Image-Tracking-Demo#2]
For some reason the project is running but the switch button and the status view controller  is hidden.

**Comment by robomex** [comment]
The placement of the buttons was hard-coded for iPhone X screen dimensions – changing the button constraints in the storyboard may help make the button visible.

I also noticed several bugs when I tried Xcode Beta 5 that broke several projects I'm working on completely.  I confirmed that others were experiencing the same breaking bugs on StackOverflow and reverted to Xcode Beta 4 – so although I cannot confirm whether this bug is related to Beta 5, I will double check whether the issue remains once Beta 6 is released and, if not, close this issue.
