### ISSUE TITLE
[Question] Retrieve images from the web?

### ISSUE THREAD

**Issue by ebellumat** [robomex/ARKit-2-Image-Tracking-Demo#3]
Exists a way to update the images assets from the web? The idea is update the capabilities of the app whitout release a new version on App Store. Exists a way to reproduce video streaming? Or, use Core ML to detect images from a model? Thanks.

**Comment by robomex** [comment]
I went down a bit of a rabbit hole below, so to answer your questions succinctly: Yes, you should be able to download assets (images, videos, etc.) from the web either on-demand or simply at app startup and then utilize/present/place those dynamic assets instead of relying on assets bundled within the app itself.  This would allow you to swap out whatever's presented in AR upon image recognition.  

Setting up that backend, retrieval, etc. is outside the scope of this demo repo – so I'd recommend finding a tutorial/library/repo that's focused on serving assets from the web to an iOS app to fill in those gaps (I'm partial to Firebase at the moment & you could probably find an applicable image-handling Firebase tutorial that would get you 90% of the way there).

---

As a diversion I looked into your particular question about video streaming instead of loading a video that's part of the app bundle itself.

From what I could tell and from my own brief testing, I wasn't able to get a WKWebView to work as the resource/view that's loaded when an image is recognized & tracked.  However, it appears like the deprecated UIWebView _does_ provide some functionality.  Check out this branch where one of the videos has been replaced with a UIWebView that loads a scrollable YouTube window over the recognized image: https://github.com/robomex/ARKit-2-Image-Tracking-Demo/tree/UIWebView

Even though some websites can be loaded (and with a bit of extra work you can create an AR browser of sorts), it doesn't look like videos can be streamed in AR using this most basic implementation of a UIWebView.  After tapping on a video in the YouTube window that pops up in the branch linked above, the videos _do_ play when they take over the entire device screen (i.e. when played not-inline), but they do not play inline as expected/desired when they're a floating AR UIWebView.

There might be some other way to create a WKWebView or something similar that allows "inline," dynamic playback in floating AR windows – but my quick search didn't turn up anything.  

Please let me know if you figure it out!
